[package]
name = "warden"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
windows.workspace = true

[target.'cfg(windows)'.dependencies]
wmi.workspace = true
winreg.workspace = true
